version: '{build}'
image: Visual Studio 2015
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true

cache:
  - packages -> **\packages.config

install:
  - ps: choco install gitversion.portable -pre -y

assembly_info:
  patch: true

nuget:
  disable_publish_on_pr: true

before_build:
  - ps: nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value

build:
  project: src/SnakeCase.JsonNet.sln
  verbosity: minimal

after_build:
  - cmd: nuget pack src\SnakeCase.JsonNet\SnakeCase.JsonNet.csproj -IncludeReferencedProjects -Build -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"
  - cmd: nuget pack src\SnakeCase.JsonNet_Portable\SnakeCase.JsonNet_Portable.csproj -IncludeReferencedProjects -Build -Version "%GitVersion_NuGetVersion%" -Prop "target=%CONFIGURATION%"

artifacts:
  - path: '*.nupkg'
    name: NuGet

deploy:
  - provider: Environment
    name: PreRelease Nuget Feed
    on:
      branch: master
  - provider: Environment
    name: Public Nuget Feed
    on:
      appveyor_repo_tag: true
